name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Type check
        run: bun run typecheck

      - name: Test
        run: bun test

      - name: Package type check
        run: bun run attw

      - name: Build Docs
        run: bun run build-docs

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run changeset-version
          publish: bun run changeset-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"

      - name: Create Pages Artifact
        if: steps.changesets.outputs.published == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: typedoc/

      - name: Deploy to GitHub Pages
        if: steps.changesets.outputs.published == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
