name: Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: ".node-version"
          cache: true

      - name: Install Dependencies
        run: vp install --frozen-lockfile

      - name: Check Formatting, Lint, and Types
        run: vp run check

      - name: Build
        run: vp run build

      - name: Type Check
        run: vp run typecheck

      - name: Test
        run: vp run test

      - name: Run Benchmarks
        run: vp run bench

      - name: Package Type Check
        run: vp run attw

      - name: Build Docs
        run: vp run build:docs

      - name: Build Examples
        run: vp run build:examples
